#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Prototipo.Resource", IsApplication=true)]

namespace Prototipo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Core.Resource.Drawable.monoandroidsplash = Prototipo.Resource.Drawable.monoandroidsplash;
			Core.Resource.Layout.monoandroidsplash = Prototipo.Resource.Layout.monoandroidsplash;
			Core.Resource.String.library_name = Prototipo.Resource.String.library_name;
			Core.Resource.Style.Mono_Android_Theme_Splash = Prototipo.Resource.Style.Mono_Android_Theme_Splash;
			Core.UI.Resource.Drawable.monoandroidsplash = Prototipo.Resource.Drawable.monoandroidsplash;
			Core.UI.Resource.Layout.monoandroidsplash = Prototipo.Resource.Layout.monoandroidsplash;
			Core.UI.Resource.String.library_name = Prototipo.Resource.String.library_name;
			Core.UI.Resource.Style.Mono_Android_Theme_Splash = Prototipo.Resource.Style.Mono_Android_Theme_Splash;
			Tabelle.Resource.Drawable.monoandroidsplash = Prototipo.Resource.Drawable.monoandroidsplash;
			Tabelle.Resource.Id.CodArea = Prototipo.Resource.Id.CodArea;
			Tabelle.Resource.Id.Descrizione = Prototipo.Resource.Id.Descrizione;
			Tabelle.Resource.Id.linearLayout1 = Prototipo.Resource.Id.linearLayout1;
			Tabelle.Resource.Id.textView1 = Prototipo.Resource.Id.textView1;
			Tabelle.Resource.Id.textView2 = Prototipo.Resource.Id.textView2;
			Tabelle.Resource.Layout.AreeUI = Prototipo.Resource.Layout.AreeUI;
			Tabelle.Resource.Layout.monoandroidsplash = Prototipo.Resource.Layout.monoandroidsplash;
			Tabelle.Resource.String.library_name = Prototipo.Resource.String.library_name;
			Tabelle.Resource.Style.Mono_Android_Theme_Splash = Prototipo.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int Aree = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int CodArea = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Descrizione = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AreeUI = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int monoandroidsplash = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Navigator = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
